### ISSUE TITLE
API 명세서

### ISSUE THREAD

**Issue by MinsuKim21** [ConvergenceSwAce/22-F-SchoolMeal#10]

**Comment by grayashh** [comment]
API_URL = https://gea662yjyk.execute-api.ap-northeast-2.amazonaws.com
이번 주 : '/info'
저번 주 :  '/prev'
다음 주 : '/next'

**Comment by MinsuKim21** [comment]
post메소드

**Comment by grayashh** [comment]
API_URL = https://gea662yjyk.execute-api.ap-northeast-2.amazonaws.com
이번 주 : '/info'
저번 주 : '/prev'
다음 주 : '/next'
설문 제출 : '/survey'
