### ISSUE TITLE
[BUG] 하시발 학식이 추가됨ㅋㅋㅋ 데이터 파싱 문제생김

### ISSUE THREAD

**Issue by MinsuKim21** [ConvergenceSwAce/22-F-SchoolMeal#53]
**버그 설명**
tlqkf 좆됨

---

**동작방식**
요일 클릭하면 값 파싱이 정상적으로 안됨

---

**스크린샷**
문제를 설명하는데 필요한 스크린샷을 추가.
![Simulator Screen Shot - iPhone 13 - 2022-10-17 at 12 01 13](https://user-images.githubusercontent.com/80405708/196080148-7d9edd6a-708d-45f8-909d-7cb1a4445b28.png)

---

**추가 컨텍스트**
다른 문제에 대한 컨텍스트를 작성

**Comment by grayashh** [comment]
Solved it
