### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MinsuKim21** [ConvergenceSwAce/22-F-SchoolMeal#84]
**버그 설명**
글자밀림 + 상단바 너무큼

---

**동작방식**
동작을 재현하는 단계:
'000 이동'
'000을 클릭'
아래로 스크롤하여 000로 이동
오류 확인
예상 동작
예상되는 상황에 대한 명확하고 간결한 작성.

---

**스크린샷**
문제를 설명하는데 필요한 스크린샷을 추가.
![1666568493135.jpg](https://user-images.githubusercontent.com/80405708/197424022-44776371-e001-4b39-acc9-40f31c6c11eb.jpg)
---

**추가 컨텍스트**
다른 문제에 대한 컨텍스트를 작성

**Comment by grayashh** [comment]
상단바는 안드로이드 같은 경우 기기마다 예외 상황이 너무 많음 -> 그래도 안드로이드만 살짝 줄이는 방향성으로 가도 될 듯
글자 밀림 같은 경우는 사용자 선호 폰트로 지정해놓은 탓에 사용자 폰트 크기에 맞춤에도 불구하고 커질 수 있음. -> 폰트 지정해야 함

**Comment by MinsuKim21** [comment]
마저 유저 폰트 사이즈
